### ISSUE TITLE
Provide ARM binaries that can run on the Raspberry Pi

### ISSUE THREAD

**Issue by mthmulders** [jodersky/flow#21] opened 2016-01-04 09:40 UTC
Following #1, I've checked to see if the shipped binaries run on the Raspberry Pi. They do not, and the JVM crashes because of that. I was able to compile the native code for ARMv6 on the Pi, and run my application with that binary.

It would be great to see a version of flow that supports the Pi out-of-the-box. Would that be possible? Is there a way I could contribute?

**Comment by jodersky** [comment] 2016-01-04 11:50
This is definitely a goal for the 2.4 release.

Up to and including 2.3, the mechanism used to load libraries from the native jar made it impossible to differentiate between the various arm platforms. The choice was made to support ARMv7 hence making it impossible to include libraries that are compatible with the Rasperry Pi. The new release uses `uname` under the hood to determine system architecture, thereby allowing a plethora of libraries to be bundled into the native jar. Since the source code of the native library is portable, it is really only a matter of compiling the library for the Raspberry Pi and including it in the native jar.

Personally, I do not have a Raspberry Pi (v1), however I would be really glad if you'd like to contribute:
- compile the native library under an ARMv6 platform, as described [here](http://www.jodersky.ch/flow/documentation/manual.html#build-process). (use the `DESTDIR=` installation method)
- archive the generated files, sign them and send them to me, I'll include them in the next release

Also, I would appreciate any feedback on issues should any arise, the current 2.4.0-M1 release is still a milestone.
Thanks!

**Comment by mthmulders** [comment] 2016-01-04 12:23
Sure, I'd be glad to help. Just to make sure: "sign them" means signing the archived files (e.g. a ZIP file) with something like PGP / GnuPG?

**Comment by jodersky** [comment] 2016-01-04 12:32
Yes, PGP would do fine.
Since we're dealing with binaries whose contents are not easily verifiable, I would like some way to check their authenticity (i.e. that the binaries you sent me are actually from you).

**Comment by mthmulders** [comment] 2016-01-05 20:59
Just to make sure... when running `./bootstrap` in `flow-native/src` the script outputs:

    aclocal: couldn't open directory 'm4': No such file or directory
    autoreconf: aclocal failed with exit status: 1

And no `configure` is generated. Am I missing something? I have the Debian packages (build-essential, autoconf, automake, libtool) installed.

**Comment by jodersky** [comment] 2016-01-06 02:30
I was able to reproduce the problem with a clean checkout. It looks as though some m4 scripts are ignored.

**Comment by jodersky** [comment] 2016-01-07 01:15
It should be fixed now

**Comment by jodersky** [comment] 2016-01-07 19:05
Thanks @mthmulders for providing an ARMv6 build! The next release should include them, expected this evening (GMT-8h).
I'll also try to do some more extensive testing in the following days as to release the final 2.4.0 version.

**Comment by jodersky** [comment] 2016-01-08 19:06
Newest release (2.4.0-M2) includes native libraries compatible with the Raspberry Pi.

**Closed by jodersky** 2016-01-08 19:06 UTC
Labels: area: native, res: community, type: enhancement

**Comment by mthmulders** [comment] 2016-01-10 19:28
First tests with 2.4.0-M2 on my Raspberry Pi seem to run fine. Thanks!

**Comment by jodersky** [comment] 2016-01-10 19:30
Awesome! Thanks for the help
